name: Github-Actions

on: push

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4.1.0
            - name: Setup Makefile
              run: make setup
            - name: Start Makefile   
              run: make start
            - name: Lint Makefile  
              run: make lint    
